In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics as met
from imblearn.over_sampling import SMOTE

import xgboost as xgb

In [5]:
df = pd.read_csv('./data/test.csv')

In [ ]:
df.returnLabel.value_counts()

In [ ]:
arry = np.genfromtxt('./data/test.csv', delimiter=',', skip_header=1)

In [6]:
col = df.columns
y = df[col[0]].values
X = df[col[1:]].values

In [ ]:
X

In [11]:
logreg = LogisticRegression(max_iter=1000)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=17)

In [8]:
# resampling the traninging data to change the balnce the data
sm = SMOTE(random_state=12)
x_res, y_res = sm.fit_sample(X_train, y_train)

In [120]:
y_res.sum(), len(y_res)

(24052, 48104)

In [12]:
model = logreg.fit(x_res, y_res)

In [122]:
y_pred = model.predict(X_test)

In [123]:
met.confusion_matrix(y_pred, y_test)

array([[5362,   32],
       [ 651,  155]])

In [129]:
met.roc_auc_score(y_test,y_pred)

0.8603057902174522

In [22]:

y_test_prob = model.predict_proba(X_test)

In [23]:
np.set_printoptions(precision=6)
np.set_printoptions(suppress=False)
y_test_prob

array([[7.089973e-01, 2.910027e-01],
       [8.344497e-01, 1.655503e-01],
       [1.000000e+00, 3.600191e-14],
       ...,
       [9.999997e-01, 2.547082e-07],
       [3.441166e-01, 6.558834e-01],
       [9.763266e-01, 2.367343e-02]])

In [24]:
np.savetxt('./data/prob_y_test.csv', y_test_prob, delimiter=',')

In [25]:
np.savetxt('./data/y_test.csv', y_test, delimiter=',')

In [124]:
y_test.sum(), y_pred.sum()

(187, 806)

In [125]:
X_test[:,2]

array([1, 1, 0, ..., 1, 1, 2])

In [126]:
unique, counts = np.unique(X_test[:,2], return_counts=True)

unique

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
xgb_model = xgb.XGBClassifier().fit(x_res, y_res)


KeyboardInterrupt: 

In [ ]:
predictions = xgb_model.predict(X_test)
actuals = y_test
print(met.confusion_matrix(actuals, predictions))

In [130]:
met.roc_auc_score(actuals,predictions)

0.7621868304947125

In [ ]:
y_test.to_sc

In [ ]:
xgb_model.predict