In [112]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics as met
from imblearn.over_sampling import SMOTE

import xgboost as xgb

In [113]:
df = pd.read_csv('./data/test.csv')

In [114]:
df.returnLabel.value_counts()

0    30065
1      935
Name: returnLabel, dtype: int64

In [102]:
arry = np.genfromtxt('./data/test.csv', delimiter=',', skip_header=1)

In [115]:
col = df.columns
y = df[col[0]].values
X = df[col[1:]].values

In [116]:
X

array([[ 60,   0,   0, ...,   0,   0,   0],
       [ 72,   1,   0, ...,   0,   0,   0],
       [ 16,   0,   0, ...,   0,   0,   0],
       ...,
       [242,   0,   1, ...,   0,   0,   0],
       [180,   0,   1, ...,   0,   0,   0],
       [ 44,   1,   0, ...,   0,   0,   0]])

In [117]:
logreg = LogisticRegression(max_iter=1000)

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=17)

In [119]:
# resampling the traninging data to change the balnce the data
sm = SMOTE(random_state=12)
x_res, y_res = sm.fit_sample(X_train, y_train)

In [120]:
y_res.sum(), len(y_res)

(24052, 48104)

In [121]:
model = logreg.fit(x_res, y_res)

In [122]:
y_pred = model.predict(X_test)

In [123]:
met.confusion_matrix(y_pred, y_test)

array([[5362,   32],
       [ 651,  155]])

In [124]:
y_test.sum(), y_pred.sum()

(187, 806)

In [125]:
X_test[:,2]

array([1, 1, 0, ..., 1, 1, 2])

In [126]:
unique, counts = np.unique(X_test[:,2], return_counts=True)

unique

array([0, 1, 2, 3, 4, 5, 6])

In [127]:
xgb_model = xgb.XGBClassifier().fit(x_res, y_res)


In [128]:
predictions = xgb_model.predict(X_test)
actuals = y_test
print(met.confusion_matrix(actuals, predictions))

[[5629  384]
 [  77  110]]
