In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics as met

import xgboost as xgb

In [2]:
df = pd.read_csv('./data/test.csv')
col = df.columns
y = df[col[0]].values
X = df[col[1:]].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=17)

In [14]:
# random undersample 

In [28]:
 unique, counts = np.unique(y_train, return_counts=True)
# we need  0 748 cases 
list(zip(counts,unique))

[(24052, 0), (748, 1)]

In [32]:
y_only_zero_only = np.array() 

TypeError: array() missing required argument 'object' (pos 1)

In [46]:
y_is_1 = y_train[y_train == 1]
y_is_0 = y_train[y_train == 0]
X_is_1 = X_train[y_train == 1]
X_is_0 = X_train[y_train == 0]
num_of_y_1 = len(y_is_1)
num_of_y_0 = len(y_is_0)

In [38]:
y_is_0.shape

(24052,)

In [37]:
y_is_1.shape

(748,)

In [40]:
X_is_1.shape

(748, 8765)

In [57]:
# undersample
np.random.seed(42)
undersample_index = np.random.choice(range(0,num_of_y_0), size=num_of_y_1, replace=False) 

In [54]:
undersample_y_0 = y_is_0[undersample_index]
undersample_x_0 = X_is_0[undersample_index]

In [60]:
undersample_y = np.concatenate((undersample_y_0, y_is_1))

In [61]:
undersample_y

array([0, 0, 0, ..., 1, 1, 1])

In [62]:
undersample_x = np.concatenate((undersample_x_0, X_is_1))

In [65]:
logreg = LogisticRegression(max_iter=1000)

In [66]:
model = logreg.fit(undersample_x, undersample_y)

In [67]:
y_pred = model.predict(X_test)

In [68]:
met.confusion_matrix(y_pred, y_test)

array([[5008,   14],
       [1005,  173]])

In [ ]:
met.roc_auc_score(y_test,y_pred)

In [70]:
# oversample
np.random.seed(17)
oversample_index = np.random.choice(range(0,num_of_y_1), size=num_of_y_0, replace=True) 

In [73]:
oversample_y_1 = y_is_1[oversample_index]
oversample_x_1 = X_is_1[oversample_index]

In [74]:
oversample_y = np.concatenate((y_is_0, oversample_y_1))
oversample_x = np.concatenate((X_is_0, oversample_x_1))

In [75]:
logreg = LogisticRegression(max_iter=1000)
model = logreg.fit(oversample_x, oversample_y)

/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [76]:
y_pred = model.predict(X_test)

In [77]:
met.confusion_matrix(y_pred, y_test)

array([[5847,   47],
       [ 166,  140]])

In [79]:
met.roc_auc_score(y_test,y_pred)

0.8605281248916118

In [81]:
1 -748/sum((748, 8765))

0.9213707558078419